### ISSUE TITLE
Just how optional would signature verification be?

### ISSUE THREAD

**Issue by jakobkummerow** [wasm-signatures/design#5]
I think I'm still lacking some clarity about what statements (from the presentation) like:

> Understandable by the runtime
> Runtime verification at load time before execution

mean. What exactly is "the runtime"? The suggested designs are putting the signatures into one or more custom sections; the convention is that custom sections may simply be ignored by tools/consumers/engines that don't understand them. But being allowed to ignore signatures defeats their purpose somewhat... 

If someone deployed a Wasm module with an invalid signature as part of a website, and a browser executed the module (instead of rejecting it due to its invalid signature), would that be considered a bug in that browser?

If an application (say, Istio) embedding a Wasm engine wanted to rely on signatures to verify Wasm modules it loads, would this application expect its embedded engine to perform signature verification? Or is this meant to be an interoperability standard for _application-level_ verification, i.e. such an application would verify any signatures it chooses to care about (disregarding any others) before handing the module off to the Wasm engine (which in turn is allowed to disregard all custom sections)?

**Comment by PiotrSikora** [comment]
> I think I'm still lacking some clarity about what statements (from the presentation) like:
> 
> > Understandable by the runtime
> > Runtime verification at load time before execution
> 
> mean. What exactly is "the runtime"?

It's really about the embedding application, not the Wasm engine itself.

> The suggested designs are putting the signatures into one or more custom sections; the convention is that custom sections may simply be ignored by tools/consumers/engines that don't understand them. But being allowed to ignore signatures defeats their purpose somewhat...
> 
> If someone deployed a Wasm module with an invalid signature as part of a website, and a browser executed the module (instead of rejecting it due to its invalid signature), would that be considered a bug in that browser?

In order to verify the signature, you need to know the public key (provided out-of-band) that you want to verify with.

On the Web, you can think about this as an evolution of [Subresource Integritoy](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity), where a link to `.wasm` module would have associated public key embedded in the HTML, and the browser would verify that the signature matches before instantiating the Wasm module.

Having said that, this proposal is driven primarly (exclusively?) by non-browser users of Wasm.

> If an application (say, Istio) embedding a Wasm engine wanted to rely on signatures to verify Wasm modules it loads, would this application expect its embedded engine to perform signature verification? Or is this meant to be an interoperability standard for _application-level_ verification, i.e. such an application would verify any signatures it chooses to care about (disregarding any others) before handing the module off to the Wasm engine (which in turn is allowed to disregard all custom sections)?

Exactly this! e.g. in Envoy, we're parsing custom sections and verifying signatures before handing off stripped bytecode to instantiate Wasm module in V8, so if the verification fails, the module never reaches the Wasm engine.

**Comment by jakobkummerow** [comment]
Cool, thanks for clarifying!

> On the Web, ...

Yeah, I suppose browser vendors could in the future develop browser-based verification schemes utilizing these signatures sections, if they decide that they are interested in that.
